######################################################################
# Automatically generated by qmake (2.01a) ?? 22. ??? 13:58:38 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += dictionarys.h
FORMS += dictionarys.ui
SOURCES += dictionarys.cpp main.cpp
RESOURCES += dictionarys.qrc
